#!/usr/bin/env python3
"""
generate_configs.py — reads config.json and produces every derived file:
  .env                              (docker-compose variable injection)
  prometheus/prometheus.yml         (from prometheus/prometheus.yml.template)
  alertmanager/alertmanager.yml     (from alertmanager/alertmanager.yml.template)
  promtail/promtail-config.yml      (from promtail/promtail-config.yml.template)

Run:  python3 generate_configs.py
      python3 generate_configs.py --check   (validate config.json only)
"""

import json
import os
import sys
import re

ROOT = os.path.dirname(os.path.abspath(__file__))


def load_config() -> dict:
    path = os.path.join(ROOT, "config.json")
    if not os.path.exists(path):
        print("ERROR: config.json not found. Copy config.example.json → config.json and fill in values.")
        sys.exit(1)
    with open(path) as f:
        return json.load(f)


def validate(cfg: dict):
    """Fail fast on CHANGE_ME placeholders and obviously wrong values."""
    errors = []
    checks = [
        ("grafana.admin_password",  "CHANGE_ME"),
        ("email.app_password",      "CHANGE_ME"),
    ]
    for key, bad in checks:
        val = get(cfg, key)
        if val and bad in str(val):
            errors.append(f"  {key} still contains placeholder '{bad}'")

    if cfg["redis"]["cache_db"] == cfg["redis"]["session_db"]:
        errors.append("  redis.cache_db and redis.session_db must be different")

    if errors:
        print("CONFIG ERRORS — fix config.json before continuing:")
        for e in errors:
            print(e)
        sys.exit(1)


def get(cfg: dict, key_path: str, default=None):
    val = cfg
    for part in key_path.split("."):
        if not isinstance(val, dict):
            return default
        val = val.get(part)
        if val is None:
            return default
    return val


def substitute(template_text: str, replacements: dict) -> str:
    """Replace all __KEY__ placeholders in the template text."""
    result = template_text
    for key, value in replacements.items():
        result = result.replace(f"__{key}__", str(value))
    # Warn on any unreplaced placeholders
    remaining = re.findall(r"__[A-Z_]+__", result)
    if remaining:
        print(f"  WARNING: unreplaced placeholders: {set(remaining)}")
    return result


def write_file(path: str, content: str):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"  wrote {os.path.relpath(path, ROOT)}")


def generate_env(cfg: dict):
    """Docker-compose reads .env for ${VAR} substitution."""
    local_ip  = cfg["network"]["local_ip"]
    lines = [
        "# Auto-generated by generate_configs.py — do not edit directly",
        f"LOCAL_IP={local_ip}",
        f"REMOTE_IP={cfg['network']['remote_ip']}",
        f"GRAFANA_ADMIN_USER={cfg['grafana']['admin_user']}",
        f"GRAFANA_ADMIN_PASSWORD={cfg['grafana']['admin_password']}",
        f"GRAFANA_PORT={cfg['ports']['grafana']}",
        f"PROMETHEUS_PORT={cfg['ports']['prometheus']}",
        f"LOKI_PORT={cfg['ports']['loki']}",
        f"ALERTMANAGER_PORT={cfg['ports']['alertmanager']}",
        f"PUSHGATEWAY_PORT={cfg['ports']['pushgateway']}",
        f"WEBHOOK_PORT={cfg['ports']['webhook']}",
        f"NODE_EXPORTER_PORT={cfg['ports']['node_exporter']}",
        f"NGINX_EXPORTER_PORT={cfg['ports']['nginx_exporter']}",
        f"CADVISOR_PORT={cfg['ports']['cadvisor']}",
        f"PLATFORM_NAME={cfg['platform']['name']}",
        f"PLATFORM_ENV={cfg['platform']['environment']}",
    ]
    write_file(os.path.join(ROOT, ".env"), "\n".join(lines) + "\n")


def generate_from_template(template_rel: str, output_rel: str, replacements: dict):
    template_path = os.path.join(ROOT, template_rel)
    output_path   = os.path.join(ROOT, output_rel)
    if not os.path.exists(template_path):
        print(f"  SKIP: template not found: {template_rel}")
        return
    with open(template_path) as f:
        content = f.read()
    write_file(output_path, substitute(content, replacements))


def main():
    check_only = "--check" in sys.argv
    cfg = load_config()

    print("Validating config.json ...")
    validate(cfg)
    print("  OK")

    if check_only:
        return

    print("\nGenerating .env ...")
    generate_env(cfg)

    # Build the master replacements dict — every template uses these
    r = {
        "LOCAL_IP":           cfg["network"]["local_ip"],
        "REMOTE_IP":          cfg["network"]["remote_ip"],
        "LOKI_PORT":          cfg["ports"]["loki"],
        "PROMETHEUS_PORT":    cfg["ports"]["prometheus"],
        "ALERTMANAGER_PORT":  cfg["ports"]["alertmanager"],
        "PUSHGATEWAY_PORT":   cfg["ports"]["pushgateway"],
        "WEBHOOK_PORT":       cfg["ports"]["webhook"],
        "NODE_EXPORTER_PORT": cfg["ports"]["node_exporter"],
        "NGINX_EXPORTER_PORT":cfg["ports"]["nginx_exporter"],
        "PROMTAIL_PORT":      cfg["ports"]["promtail"],
        "SMTP_HOST":          cfg["email"]["smtp_host"],
        "SMTP_FROM":          cfg["email"]["from_address"],
        "SMTP_USER":          cfg["email"]["from_address"],
        "SMTP_PASSWORD":      cfg["email"]["app_password"],
        "EMAIL_P1":           cfg["email"]["recipients"]["p1"],
        "EMAIL_P2":           cfg["email"]["recipients"]["p2"],
        "EMAIL_P3":           cfg["email"]["recipients"]["p3"],
        "EMAIL_CORR":         cfg["email"]["recipients"]["correlation"],
        "WEBHOOK_TOKEN":      cfg["webhook"]["secret_token"],
        "PLATFORM_NAME":      cfg["platform"]["name"],
        "INSTANCE_NAME":      cfg["platform"]["instance_name"],
        "PLATFORM_ENV":       cfg["platform"]["environment"],
    }

    print("\nGenerating prometheus/prometheus.yml ...")
    generate_from_template("prometheus/prometheus.yml.template", "prometheus/prometheus.yml", r)

    print("\nGenerating alertmanager/alertmanager.yml ...")
    generate_from_template("alertmanager/alertmanager.yml.template", "alertmanager/alertmanager.yml", r)

    print("\nGenerating promtail/promtail-config.yml ...")
    generate_from_template("promtail/promtail-config.yml.template", "promtail/promtail-config.yml", r)

    print("\nAll configs generated successfully.")
    print("Next step:  docker-compose up -d")


if __name__ == "__main__":
    main()
